version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: eros-postgres
    restart: always
    environment:
      POSTGRES_DB: eros
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: eros-redis
    ports:
      - "6379:6379"
    restart: always
  profile-service:
    build: ./src/server/ProfileService_nam
    container_name: eros-profile
    ports:
      - "4000:4000"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: 123456
      DB_NAME: eros
    depends_on:
      - postgres
    restart: always
  chat-service:
    build: ./src/server/chatService_baanh
    container_name: eros-chat
    ports:
      - "8005:8005"
    depends_on:
      - postgres
      - redis
    restart: always

  match-service:
    build: ./backend/matchservice_hoa
    container_name: eros-match
    ports:
      - "8006:8006"
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - ./backend/matchservice_hoa/.env
  auth-service:
    build: ./src/server/authService_bach
    container_name: eros-auth
    ports:
      - "8007:8007"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: 123456
      DB_NAME: eros
    depends_on:
      - postgres
    restart: always
    env_file:
      - ./src/server/authService_bach/.env

  photo-server:
    build: ./src/server/photoService_bach
    container_name: eros-photo
    ports:
      - "8008:8008"
    depends_on:
      - postgres
    volumes:
      - eros_uploads:/app/uploads
    restart: always
volumes:
  postgres_data:
  eros_uploads:
  
